/**
 * Renders the demo's synthetic document images.
 *
 * Rendered from code rather than edited from a photograph, for two reasons.
 * It is reproducible — anyone can regenerate these and see exactly what is
 * in them. And it cannot accidentally be a convincing replica of a
 * government ID, which is not a thing to publish in a public repository.
 *
 * The card below carries a prominent SPECIMEN watermark, a synthetic name, a
 * synthetic (though Verhoeff-valid) number, and deliberately no UIDAI logo
 * and no national emblem. It needs to be *readable* by OCR, not convincing
 * to a person.
 */
import { writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const here = dirname(fileURLToPath(import.meta.url));

// --- Verhoeff, so the number is real work for the detector ----------------
const D = [[0,1,2,3,4,5,6,7,8,9],[1,2,3,4,0,6,7,8,9,5],[2,3,4,0,1,7,8,9,5,6],
           [3,4,0,1,2,8,9,5,6,7],[4,0,1,2,3,9,5,6,7,8],[5,9,8,7,6,0,4,3,2,1],
           [6,5,9,8,7,1,0,4,3,2],[7,6,5,9,8,2,1,0,4,3],[8,7,6,5,9,3,2,1,0,4],
           [9,8,7,6,5,4,3,2,1,0]];
const P = [[0,1,2,3,4,5,6,7,8,9],[1,5,7,6,2,8,3,0,9,4],[5,8,0,3,7,9,6,1,4,2],
           [8,9,1,6,0,4,3,5,2,7],[9,4,5,3,1,2,6,8,7,0],[4,2,8,6,5,7,3,9,0,1],
           [2,7,9,3,8,0,6,4,1,5],[7,0,4,6,9,1,3,2,5,8]];
const INV = [0,4,3,2,1,5,6,7,8,9];

const checkDigit = (body) => {
  let c = 0;
  [...(body + '0')].reverse().forEach((ch, i) => { c = D[c][P[i % 8][Number(ch)]]; });
  return String(INV[c]);
};
const verhoeffOk = (d) => {
  let c = 0;
  [...d].reverse().forEach((ch, i) => { c = D[c][P[i % 8][Number(ch)]]; });
  return c === 0;
};

const BODY = '31840275916';
export const SPECIMEN_AADHAAR = BODY + checkDigit(BODY);
if (!verhoeffOk(SPECIMEN_AADHAAR)) {
  throw new Error('specimen number is not Verhoeff-valid; OCR would have nothing to prove');
}

const grouped = SPECIMEN_AADHAAR.replace(/(\d{4})(?=\d)/g, '$1 ');

// Devanagari, spelled out so the file stays readable in any editor.
const HI_GOVT   = 'भारत सरकार';   // भारत सरकार
const HI_AADHAAR = 'आधार';                                  // आधार
const HI_NAME   = 'आशा वर्मा';         // आशा वर्मा
const HI_DOB    = 'जन्म तिथि';         // जन्म तिथि

const W = 520, H = 320;

const card = `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}" role="img" aria-label="Specimen identity card, synthetic">
  <defs>
    <pattern id="mark" width="260" height="150" patternUnits="userSpaceOnUse" patternTransform="rotate(-24)">
      <text x="0" y="60" font-family="Helvetica, Arial, sans-serif" font-size="34"
            font-weight="700" fill="#c9302c" opacity="0.20">SPECIMEN</text>
    </pattern>
  </defs>

  <rect width="${W}" height="${H}" fill="#fdfcf7" stroke="#9aa0a6" stroke-width="2"/>
  <rect x="0" y="0" width="${W}" height="54" fill="#f2efe6"/>

  <!-- No emblem, no logo: this must read as a specimen, not a replica. -->
  <text x="24" y="26" font-family="Noto Sans Devanagari, Devanagari Sangam MN, sans-serif"
        font-size="17" fill="#1a1a1a">${HI_GOVT}</text>
  <text x="24" y="46" font-family="Helvetica, Arial, sans-serif"
        font-size="15" fill="#1a1a1a">GOVERNMENT OF INDIA — SPECIMEN ONLY</text>

  <rect x="24" y="76" width="112" height="132" fill="#e4e1d8" stroke="#9aa0a6"/>
  <text x="80" y="146" text-anchor="middle" font-family="Helvetica, Arial, sans-serif"
        font-size="12" fill="#6b6b6b">PHOTO</text>

  <text x="160" y="98" font-family="Noto Sans Devanagari, Devanagari Sangam MN, sans-serif"
        font-size="20" fill="#1a1a1a">${HI_NAME}</text>
  <text x="160" y="124" font-family="Helvetica, Arial, sans-serif"
        font-size="19" fill="#1a1a1a">Asha Verma</text>
  <text x="160" y="152" font-family="Noto Sans Devanagari, Devanagari Sangam MN, sans-serif"
        font-size="15" fill="#3c3f47">${HI_DOB}: 14/03/1992</text>
  <text x="160" y="174" font-family="Helvetica, Arial, sans-serif"
        font-size="15" fill="#3c3f47">DOB: 14/03/1992   Female</text>

  <text x="24" y="246" font-family="Noto Sans Devanagari, Devanagari Sangam MN, sans-serif"
        font-size="20" fill="#1a1a1a">${HI_AADHAAR}</text>
  <text x="24" y="284" font-family="Helvetica, Arial, sans-serif"
        font-size="30" font-weight="700" letter-spacing="2" fill="#111">${grouped}</text>

  <text x="${W - 22}" y="${H - 12}" text-anchor="end"
        font-family="Helvetica, Arial, sans-serif" font-size="11" fill="#8a8a8a">
    Synthetic specimen — not a real document — generated by demo/build-assets.mjs
  </text>

  <rect width="${W}" height="${H}" fill="url(#mark)"/>
</svg>
`;

writeFileSync(resolve(here, 'assets/specimen-aadhaar.svg'), card);

console.log('Wrote demo/assets/specimen-aadhaar.svg');
console.log(`  specimen number ${SPECIMEN_AADHAAR}  (Verhoeff-valid: ${verhoeffOk(SPECIMEN_AADHAAR)})`);
